

name: MyActions

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} 
          files: ./coverage1.xml,./coverage2.xml 
          flags: unittests # optional
      - name: Upload coverage results to Codecov.io
        uses: codecov/codecov-action@v2
        with:
            token: ${{secrets.CODECOV_TOKEN}}
            version: "v0.1.15"
